In [1]:
import numpy as np
import pandas as pd
df=pd.read_excel("superstore.xlsx")
df.head()

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,State,Postal_Code,Region,Product_ID,Category,Sub_Category,Product_Name,Sales
0,1,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,2017-06-12,2017-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

In [2]:
df_flat=df.groupby("Customer_ID").agg(Customer_Name= ("Customer_Name","first"), Total_Spend=("Sales","sum")).sort_values(by="Total_Spend", ascending=False).reset_index()
df_flat.head(10)

  Customer_ID       Customer_Name  Total_Spend
0    SM-20320         Sean Miller    25043.050
1    TC-20980        Tamara Chand    19052.218
2    RB-19360        Raymond Buch    15117.339
3    TA-21385        Tom Ashbrook    14595.620
4    AB-10105       Adrian Barton    14473.571
5    KL-16645        Ken Lonsdale    14175.229
6    SC-20095        Sanjit Chand    14142.334
7    HL-15040        Hunter Lopez    12873.298
8    SE-20110        Sanjit Engle    12209.438
9    CC-12370  Christopher Conant    12129.072

In [3]:
Total_Sales=df["Sales"].sum()
print(f"${Total_Sales:,.2f}")

$2,261,536.78

In [4]:
Pareto = (df_flat["Total_Spend"] / Total_Sales) * 100
print(Pareto.head(10))

0    1.107347
1    0.842446
2    0.668454
3    0.645385
4    0.639988
5    0.626796
6    0.625342
7    0.569228
8    0.539874
9    0.536320
Name: Total_Spend, dtype: float64

In [5]:
Total_Orders=df["Order_ID"].nunique()
print(Total_Orders)

4922

In [6]:
Latest_Purchase_Date=df[["Customer_Name","Order_Date"]].sort_values(by="Order_Date",ascending=False).head(1)
print(Latest_Purchase_Date)

         Customer_Name Order_Date
906  Patrick O'Donnell 2018-12-30

In [7]:
AOV=Total_Sales/Total_Orders
print(f"${AOV:.2f}")

$459.48

In [8]:
Running_Total=Pareto.cumsum()
print(Running_Total)

0        1.107347
1        1.949792
2        2.618246
3        3.263632
4        3.903620
          ...
788     99.998197
789     99.998928
790     99.999552
791     99.999786
792    100.000000
Name: Total_Spend, Length: 793, dtype: float64

In [9]:
import pandas as pd
pd.set_option("display.float_format", lambda x: "%.2f" % x)
df_flat["Pareto_Percentage"] = Running_Total
df_flat["Spend_Percentage_Of_Total"] = Pareto
df_flat["Total_Orders"] = Total_Orders
df_flat["Average_Order_Value"] = AOV
df_flat["Total_Sales"] = Total_Sales
df_flat

,Customer_ID,Customer_Name,Total_Spend,Pareto_Percentage,Spend_Percentage_Of_Total,Total_Orders,Average_Order_Value,Total_Sales
0,SM-20320,Sean Miller,25043.05,1.11,1.11,4922,459.48,2261536.78
1,TC-20980,Tamara Chand,19052.22,1.95,0.84,4922,459.48,2261536.78
2,RB-19360,Raymond Buch,15117.34,2.62,0.67,4922,459.48,2261536.78
3,TA-21385,Tom Ashbrook,14595.62,3.26,0.65,4922,459.48,2261536.78
4,AB-10105,Adrian Barton,14473.57,3.90,0.64,4922,459.48,2261536.78
...,...,...,...,...,...,...,...,...
788,MG-18205,Mitch Gastineau,16.74,100.00,0.00,4922,459.48,2261536.78
789,CJ-11875,Carl Jackson,16.52,100.00,0.00,4922,459.48,2261536.78
790,SC-20845,Sung Chung,14.11,100.00,0.00,4922,459.48,2261536.78
791,LD-16855,Lela Donovan,5.30,100.00,0.00,4922,459.48,2261536.78
792,TS-21085,Thais Sissman,4.83,100.00,0.00,4922,459.48,2261536.78

In [10]:
df_flat["Orders_per_Customer"]=df.groupby("Customer_ID")["Order_ID"].nunique().values
df_flat.head()

,Customer_ID,Customer_Name,Total_Spend,Pareto_Percentage,Spend_Percentage_Of_Total,Total_Orders,Average_Order_Value,Total_Sales,Orders_per_Customer
0,SM-20320,Sean Miller,25043.05,1.11,1.11,4922,459.48,2261536.78,5
1,TC-20980,Tamara Chand,19052.22,1.95,0.84,4922,459.48,2261536.78,9
2,RB-19360,Raymond Buch,15117.34,2.62,0.67,4922,459.48,2261536.78,4
3,TA-21385,Tom Ashbrook,14595.62,3.26,0.65,4922,459.48,2261536.78,6
4,AB-10105,Adrian Barton,14473.57,3.90,0.64,4922,459.48,2261536.78,3

In [11]:
df_flat["Last_Purchase"]=(df.groupby("Customer_ID")["Order_Date"].max().values)
df_flat

,Customer_ID,Customer_Name,Total_Spend,Pareto_Percentage,Spend_Percentage_Of_Total,Total_Orders,Average_Order_Value,Total_Sales,Orders_per_Customer,Last_Purchase
0,SM-20320,Sean Miller,25043.05,1.11,1.11,4922,459.48,2261536.78,5,2018-06-29
1,TC-20980,Tamara Chand,19052.22,1.95,0.84,4922,459.48,2261536.78,9,2018-12-11
2,RB-19360,Raymond Buch,15117.34,2.62,0.67,4922,459.48,2261536.78,4,2018-04-15
3,TA-21385,Tom Ashbrook,14595.62,3.26,0.65,4922,459.48,2261536.78,6,2018-11-05
4,AB-10105,Adrian Barton,14473.57,3.90,0.64,4922,459.48,2261536.78,3,2017-11-10
...,...,...,...,...,...,...,...,...,...,...
788,MG-18205,Mitch Gastineau,16.74,100.00,0.00,4922,459.48,2261536.78,11,2018-11-17
789,CJ-11875,Carl Jackson,16.52,100.00,0.00,4922,459.48,2261536.78,5,2018-12-26
790,SC-20845,Sung Chung,14.11,100.00,0.00,4922,459.48,2261536.78,8,2018-12-21
791,LD-16855,Lela Donovan,5.30,100.00,0.00,4922,459.48,2261536.78,13,2018-11-06
792,TS-21085,Thais Sissman,4.83,100.00,0.00,4922,459.48,2261536.78,5,2018-06-11

In [12]:
latestdate=df["Order_Date"].max()
print(latestdate)

2018-12-30 00:00:00

In [13]:
df_flat["Days_Without_Ordering"]=(latestdate-df_flat["Last_Purchase"]).dt.days
df_flat

,Customer_ID,Customer_Name,Total_Spend,Pareto_Percentage,Spend_Percentage_Of_Total,Total_Orders,Average_Order_Value,Total_Sales,Orders_per_Customer,Last_Purchase,Days_Without_Ordering
0,SM-20320,Sean Miller,25043.05,1.11,1.11,4922,459.48,2261536.78,5,2018-06-29,184
1,TC-20980,Tamara Chand,19052.22,1.95,0.84,4922,459.48,2261536.78,9,2018-12-11,19
2,RB-19360,Raymond Buch,15117.34,2.62,0.67,4922,459.48,2261536.78,4,2018-04-15,259
3,TA-21385,Tom Ashbrook,14595.62,3.26,0.65,4922,459.48,2261536.78,6,2018-11-05,55
4,AB-10105,Adrian Barton,14473.57,3.90,0.64,4922,459.48,2261536.78,3,2017-11-10,415
...,...,...,...,...,...,...,...,...,...,...,...
788,MG-18205,Mitch Gastineau,16.74,100.00,0.00,4922,459.48,2261536.78,11,2018-11-17,43
789,CJ-11875,Carl Jackson,16.52,100.00,0.00,4922,459.48,2261536.78,5,2018-12-26,4
790,SC-20845,Sung Chung,14.11,100.00,0.00,4922,459.48,2261536.78,8,2018-12-21,9
791,LD-16855,Lela Donovan,5.30,100.00,0.00,4922,459.48,2261536.78,13,2018-11-06,54
792,TS-21085,Thais Sissman,4.83,100.00,0.00,4922,459.48,2261536.78,5,2018-06-11,202

In [14]:
condition=[(df_flat['Orders_per_Customer'] >= 6) & (df_flat['Days_Without_Ordering'] <= 180),
             (df_flat['Orders_per_Customer'] >= 3) & (df_flat['Orders_per_Customer'] < 6) & (df_flat['Days_Without_Ordering'] <= 180),
           (df_flat['Orders_per_Customer'] >= 3) & (df_flat['Days_Without_Ordering'] > 180),
           (df_flat['Orders_per_Customer'] < 3) & (df_flat['Days_Without_Ordering'] <= 180)
          ]
choices=['Frequent Flyer (VIP)', 'Regular Customer', 'High-Value Churn Risk', 'New / Occasional']
df_flat["Customer Segment"]=np.select(condition, choices, default='Sleeper / Inactive')
df_flat["Customer Segment"].value_counts()

Customer Segment
Frequent Flyer (VIP)     390
Regular Customer         183
High-Value Churn Risk    173
Sleeper / Inactive        29
New / Occasional          18
Name: count, dtype: int64

In [15]:
df_flat

,Customer_ID,Customer_Name,Total_Spend,Pareto_Percentage,Spend_Percentage_Of_Total,Total_Orders,Average_Order_Value,Total_Sales,Orders_per_Customer,Last_Purchase,Days_Without_Ordering,Customer Segment
0,SM-20320,Sean Miller,25043.05,1.11,1.11,4922,459.48,2261536.78,5,2018-06-29,184,High-Value Churn Risk
1,TC-20980,Tamara Chand,19052.22,1.95,0.84,4922,459.48,2261536.78,9,2018-12-11,19,Frequent Flyer (VIP)
2,RB-19360,Raymond Buch,15117.34,2.62,0.67,4922,459.48,2261536.78,4,2018-04-15,259,High-Value Churn Risk
3,TA-21385,Tom Ashbrook,14595.62,3.26,0.65,4922,459.48,2261536.78,6,2018-11-05,55,Frequent Flyer (VIP)
4,AB-10105,Adrian Barton,14473.57,3.90,0.64,4922,459.48,2261536.78,3,2017-11-10,415,High-Value Churn Risk
...,...,...,...,...,...,...,...,...,...,...,...,...
788,MG-18205,Mitch Gastineau,16.74,100.00,0.00,4922,459.48,2261536.78,11,2018-11-17,43,Frequent Flyer (VIP)
789,CJ-11875,Carl Jackson,16.52,100.00,0.00,4922,459.48,2261536.78,5,2018-12-26,4,Regular Customer
790,SC-20845,Sung Chung,14.11,100.00,0.00,4922,459.48,2261536.78,8,2018-12-21,9,Frequent Flyer (VIP)
791,LD-16855,Lela Donovan,5.30,100.00,0.00,4922,459.48,2261536.78,13,2018-11-06,54,Frequent Flyer (VIP)
792,TS-21085,Thais Sissman,4.83,100.00,0.00,4922,459.48,2261536.78,5,2018-06-11,202,High-Value Churn Risk

In [16]:
import pandas as pd
df_flat["R_Score"] = pd.qcut(
    df_flat["Days_Without_Ordering"], q=5, labels=[5, 4, 3, 2, 1]
)
df_flat["F_Score"] = pd.qcut(
    df_flat["Orders_per_Customer"], q=5, labels=[1, 2, 3, 4, 5], duplicates="drop"
)
df_flat["M_Score"] = pd.qcut(
    df_flat["Total_Spend"], q=5, labels=[1, 2, 3, 4, 5]
)

In [17]:
df_flat

,Customer_ID,Customer_Name,Total_Spend,Pareto_Percentage,Spend_Percentage_Of_Total,Total_Orders,Average_Order_Value,Total_Sales,Orders_per_Customer,Last_Purchase,Days_Without_Ordering,Customer Segment,R_Score,F_Score,M_Score
0,SM-20320,Sean Miller,25043.05,1.11,1.11,4922,459.48,2261536.78,5,2018-06-29,184,High-Value Churn Risk,2,2,5
1,TC-20980,Tamara Chand,19052.22,1.95,0.84,4922,459.48,2261536.78,9,2018-12-11,19,Frequent Flyer (VIP),5,5,5
2,RB-19360,Raymond Buch,15117.34,2.62,0.67,4922,459.48,2261536.78,4,2018-04-15,259,High-Value Churn Risk,1,1,5
3,TA-21385,Tom Ashbrook,14595.62,3.26,0.65,4922,459.48,2261536.78,6,2018-11-05,55,Frequent Flyer (VIP),3,3,5
4,AB-10105,Adrian Barton,14473.57,3.90,0.64,4922,459.48,2261536.78,3,2017-11-10,415,High-Value Churn Risk,1,1,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
788,MG-18205,Mitch Gastineau,16.74,100.00,0.00,4922,459.48,2261536.78,11,2018-11-17,43,Frequent Flyer (VIP),4,5,1
789,CJ-11875,Carl Jackson,16.52,100.00,0.00,4922,459.48,2261536.78,5,2018-12-26,4,Regular Customer,5,2,1
790,SC-20845,Sung Chung,14.11,100.00,0.00,4922,459.48,2261536.78,8,2018-12-21,9,Frequent Flyer (VIP),5,4,1
791,LD-16855,Lela Donovan,5.30,100.00,0.00,4922,459.48,2261536.78,13,2018-11-06,54,Frequent Flyer (VIP),3,5,1
792,TS-21085,Thais Sissman,4.83,100.00,0.00,4922,459.48,2261536.78,5,2018-06-11,202,High-Value Churn Risk,2,2,1

In [18]:
df_flat['RFM_Score'] = df_flat['R_Score'].astype(str) + df_flat['F_Score'].astype(str) + df_flat['M_Score'].astype(str)

In [19]:
df_flat

,Customer_ID,Customer_Name,Total_Spend,Pareto_Percentage,Spend_Percentage_Of_Total,Total_Orders,Average_Order_Value,Total_Sales,Orders_per_Customer,Last_Purchase,Days_Without_Ordering,Customer Segment,R_Score,F_Score,M_Score,RFM_Score
0,SM-20320,Sean Miller,25043.05,1.11,1.11,4922,459.48,2261536.78,5,2018-06-29,184,High-Value Churn Risk,2,2,5,225
1,TC-20980,Tamara Chand,19052.22,1.95,0.84,4922,459.48,2261536.78,9,2018-12-11,19,Frequent Flyer (VIP),5,5,5,555
2,RB-19360,Raymond Buch,15117.34,2.62,0.67,4922,459.48,2261536.78,4,2018-04-15,259,High-Value Churn Risk,1,1,5,115
3,TA-21385,Tom Ashbrook,14595.62,3.26,0.65,4922,459.48,2261536.78,6,2018-11-05,55,Frequent Flyer (VIP),3,3,5,335
4,AB-10105,Adrian Barton,14473.57,3.90,0.64,4922,459.48,2261536.78,3,2017-11-10,415,High-Value Churn Risk,1,1,5,115
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
788,MG-18205,Mitch Gastineau,16.74,100.00,0.00,4922,459.48,2261536.78,11,2018-11-17,43,Frequent Flyer (VIP),4,5,1,451
789,CJ-11875,Carl Jackson,16.52,100.00,0.00,4922,459.48,2261536.78,5,2018-12-26,4,Regular Customer,5,2,1,521
790,SC-20845,Sung Chung,14.11,100.00,0.00,4922,459.48,2261536.78,8,2018-12-21,9,Frequent Flyer (VIP),5,4,1,541
791,LD-16855,Lela Donovan,5.30,100.00,0.00,4922,459.48,2261536.78,13,2018-11-06,54,Frequent Flyer (VIP),3,5,1,351
792,TS-21085,Thais Sissman,4.83,100.00,0.00,4922,459.48,2261536.78,5,2018-06-11,202,High-Value Churn Risk,2,2,1,221

In [20]:
df_final = pd.merge(df, df_flat, on=["Customer_ID", "Customer_Name"], how="left")
df_final.head()

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,...,Average_Order_Value,Total_Sales,Orders_per_Customer,Last_Purchase,Days_Without_Ordering,Customer Segment,R_Score,F_Score,M_Score,RFM_Score
0,1,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,459.48,2261536.78,2,2017-02-11,687,Sleeper / Inactive,1,1,2,112
1,2,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,459.48,2261536.78,2,2017-02-11,687,Sleeper / Inactive,1,1,2,112
2,3,CA-2017-138688,2017-06-12,2017-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,459.48,2261536.78,6,2018-06-17,196,High-Value Churn Risk,2,3,2,232
3,4,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,459.48,2261536.78,8,2018-08-01,151,Frequent Flyer (VIP),2,4,3,243
4,5,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,459.48,2261536.78,8,2018-08-01,151,Frequent Flyer (VIP),2,4,3,243

In [21]:
df_flat.to_excel("Customer_Results_df_flat.xlsx", index=False)
df_final.to_excel("Customer_Results_df_final.xlsx", index=False)